// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN2FDFc3qqQ8a5z4kuhkNO_J5F6VrwQkQ',
    appId: '1:962134897979:web:a7792f04980d6f85f4331e',
    messagingSenderId: '962134897979',
    projectId: 'fir-connection-f3386',
    authDomain: 'fir-connection-f3386.firebaseapp.com',
    storageBucket: 'fir-connection-f3386.appspot.com',
    measurementId: 'G-PENP96ZMWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPgMNyaLDl17R0V7e0BpVsCcbSlBzCxIc',
    appId: '1:962134897979:android:74be772fb5dec49df4331e',
    messagingSenderId: '962134897979',
    projectId: 'fir-connection-f3386',
    storageBucket: 'fir-connection-f3386.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoUn2b8AV-W0y_SkK6qjGr-e-XRHdfmJM',
    appId: '1:962134897979:ios:307c2e10f419ac24f4331e',
    messagingSenderId: '962134897979',
    projectId: 'fir-connection-f3386',
    storageBucket: 'fir-connection-f3386.appspot.com',
    iosBundleId: 'com.example.firebaseconnection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoUn2b8AV-W0y_SkK6qjGr-e-XRHdfmJM',
    appId: '1:962134897979:ios:307c2e10f419ac24f4331e',
    messagingSenderId: '962134897979',
    projectId: 'fir-connection-f3386',
    storageBucket: 'fir-connection-f3386.appspot.com',
    iosBundleId: 'com.example.firebaseconnection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCN2FDFc3qqQ8a5z4kuhkNO_J5F6VrwQkQ',
    appId: '1:962134897979:web:72b7b3176210e7b5f4331e',
    messagingSenderId: '962134897979',
    projectId: 'fir-connection-f3386',
    authDomain: 'fir-connection-f3386.firebaseapp.com',
    storageBucket: 'fir-connection-f3386.appspot.com',
    measurementId: 'G-Q5J3DY7V4C',
  );
}
